### ISSUE TITLE
Out of memory exception in v1.4.9

### ISSUE THREAD

**Issue by shanadas** [thomaslevesque/WpfAnimatedGif#10]
I am getting following exception randomly when I create random number of instances (less than 25) of a custom control with WpfAnimatedGif control. Exception stack trace below, highlighted some lines.

>at System.Windows.Media.Imaging.BitmapSource.CreateCachedBitmap(BitmapFrame frame, BitmapSourceSafeMILHandle wicSource, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, BitmapPalette palette)
   at System.Windows.Media.Imaging.RenderTargetBitmap.CopyCommon(RenderTargetBitmap sourceBitmap)
   at System.Windows.Media.Imaging.RenderTargetBitmap.CloneCurrentValueCore(Freezable sourceFreezable)
   at System.Windows.Freezable.CloneCoreCommon(Freezable sourceFreezable, Boolean useCurrentValue, Boolean cloneFrozenValues)
   at System.Windows.Freezable.CloneCurrentValueCore(Freezable sourceFreezable)
   at System.Windows.Freezable.CloneCurrentValue()
   at System.Windows.Media.Animation.ObjectKeyFrameCollection.CloneCurrentValueCore(Freezable sourceFreezable)
   at System.Windows.Freezable.CloneCurrentValue()
   at System.Windows.Media.Animation.ObjectAnimationUsingKeyFrames.CopyCommon(ObjectAnimationUsingKeyFrames sourceAnimation, Boolean isCurrentValueClone)
   at System.Windows.Media.Animation.ObjectAnimationUsingKeyFrames.GetCurrentValueAsFrozenCore(Freezable source)
   at System.Windows.Freezable.GetCurrentValueAsFrozen()
   at System.Windows.Media.Animation.Clock..ctor(Timeline timeline)
   at System.Windows.Media.Animation.AnimationTimeline.AllocateClock()
   at System.Windows.Media.Animation.Clock.AllocateClock(Timeline timeline, Boolean hasControllableRoot)
   at System.Windows.Media.Animation.Clock.BuildClockTreeFromTimeline(Timeline rootTimeline, Boolean hasControllableRoot)
   at System.Windows.Media.Animation.AnimationTimeline.CreateClock()
   **_at WpfAnimatedGif.ImageAnimationController..ctor(Image image, ObjectAnimationUsingKeyFrames animation, Boolean autoStart)
   at WpfAnimatedGif.ImageBehavior.InitAnimationOrImage(Image imageControl)
   at WpfAnimatedGif.ImageBehavior.<>c__DisplayClasse`1.<DoWhenLoaded>b__b(Object sender, RoutedEventArgs e)_**
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()

**Comment by thomaslevesque** [comment]
No response from OP in more than 6 months, closing
