### ISSUE TITLE
Support for Windows 10

### ISSUE THREAD

**Issue by GyleIverson** [thomaslevesque/WpfAnimatedGif#18]
I tried installing through NuGet into a Windows 10 Universal project and it fails.

Wondering if you have tried targeting a Windows 10 Universal build?

Any suggestions?

Thanks,
Gyle

Here is the Package Manager Output:
Attempting to gather dependencies information for package 'XamlAnimatedGif.1.0.0-beta2' with respect to project targeting 'Windows, Version=v8.1'
Attempting to resolve dependencies for package 'XamlAnimatedGif.1.0.0-beta2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'XamlAnimatedGif.1.0.0-beta2'
Resolved actions to install package 'XamlAnimatedGif.1.0.0-beta2'
For adding package 'XamlAnimatedGif 1.0.0-beta2' to project 'CyberDustUniversal' that targets 'win81'.
For adding package 'XamlAnimatedGif 1.0.0-beta2' to project 'CyberDustUniversal' that targets 'win81'.
Package 'XamlAnimatedGif 1.0.0-beta2' already exists in folder 'C:\cyberdust\branches\windows10\CyberDust\packages'
Install failed. Rolling back...
System.InvalidOperationException: Failed to add reference to 'XamlAnimatedGif'. ---> System.Runtime.InteropServices.COMException: Project unavailable.
   at EnvDTE.Project.get_Object()
   at NuGet.PackageManagement.VisualStudio.EnvDTEProjectUtility.GetReferences(Project project)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddReference(String referencePath)
   --- End of inner exception stack trace ---
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__ea.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActions>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformAction>d__0.MoveNext()
========== Finished ==========

**Comment by thomaslevesque** [comment]
Hi,

Looks like you posted to the wrong project; this error is about XamlAnimatedGif, not WpfAnimatedGif. WpfAnimatedGif, as the name implies, only targets WPF.

[XamlAnimatedGif](https://github.com/thomaslevesque/XamlAnimatedGif), on the other hand, supports multiple XAML platforms, including WPF, Windows Phone 8.1 and Windows 8.1. I intend to support Windows 10 Universal Apps as well, but I haven't started to work on this yet, so at this point you can't use it in a Universal App.
